---
abstract: 'is a ready to use Codio box. Start coding now!'
author:
  - 'G. Casati <fibo@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: '6.64'
  Test::Compile: v1.2.1
  Test::More: '1.001009'
  Test::Pod: '1.48'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.04, CPAN::Meta::Converter version 2.143240'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Perl-Box
no_index:
  directory:
    - t
    - inc
requires:
  App::FatPacker: '0.010002'
  Catalyst::Devel: '1.39'
  DBI: '1.633'
  DBIx::Class: '0.082810'
  Dancer: '1.3132'
  DateTime: '1.18'
  Dist::Zilla: '5.031'
  Mojolicious: '5.77'
  Moo: '1.007000'
  Moose: '2.1403'
  Task::BeLike::FIBO: '0.14'
  Template: '2.26'
  Test::Class: '0.48'
  Test::Most: '0.34'
  YAML: '1.14'
  perl: '5.20'
resources:
  bugtracker: https://github.com/fibo/Perl-Box-pm/issues
  homepage: https://metacpan.org/pod/Perl::Box
  license: http://g14n.info/artistic-license
  repository: https://github.com/fibo/Perl-Box-pm
version: '0.01'
